services:
  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - frontend
  backend:
    build:
      context:
        ./backend
      dockerfile: 
        Dockerfile.prod

  frontend:
    build:
      context:
        ./frontend
      dockerfile: 
        Dockerfile.prod